### ISSUE TITLE
Allow disabling transitions for manual resize/move (i.e. click and drag/alt+drag)

### ISSUE THREAD

**Issue by freddyhayward** [rliang/gnome-shell-extension-window-animations#3]
This extension is perfect for maximise/restore/tiling, but becomes really annoying when resizing or moving a window manually. Please allow us to turn this off so manual resizing isn't affected.

**Comment by rliang** [comment]
Indeed, it shouldn't affect manual resizing.

**Comment by freddyhayward** [comment]
Does this also apply to movement?

**Comment by rliang** [comment]
Yup.
