### ISSUE TITLE
Animation isn't always nice on xorg

### ISSUE THREAD

**Issue by Naheel-Azawy** [rliang/gnome-shell-extension-window-animations#5]
Fedora 26
GNOME 3.24
Enjoy the video
https://youtu.be/nRvBMvGvLWs
Nice: Chrome, SimpleScreenRecorder, Eclipse, Android Studio
Not really: Gnome Software, Builder, Evince
Bad: System monitor, Nautilus, Lollypop

**Comment by rliang** [comment]
Hi,

There seem to be differences in how GNOME handles window resizing for windows with Server-Side Decorations (SSD) and windows with Client-Side Decorations (CSD). The ones you listed as nice all use SSD.

However, animations are smooth for Nautilus here. What graphics driver are you using, Nvidia, Intel...?

**Comment by Naheel-Azawy** [comment]
Intel® HD Graphics 5500 (Broadwell GT2) / AMD® Iceland
By the way, the animation is always smooth even for those which were mentioned as "bad" except when maximizing. Take a look https://youtu.be/oYtjbG30Zi8

**Comment by rliang** [comment]
I still can't reproduce the behavior on maximizing. I'm on Intel Ivy Bridge graphics, so I can only infer that it's an issue with Broadwell driver support, or maybe another extension is doing some work when you maximize windows...

**Comment by medicamin** [comment]
I have also problems with some native gnome animations, such az maximization in totem.

Gnome 3.24
Manjaro

**Comment by Naheel-Azawy** [comment]
I tried it today with wayland and it seems to be working pretty well. I have no idea why but apparently it doesn't work well with xorg.
Title updated

**Comment by rliang** [comment]
@Naheel-Azawy thanks for the heads-up!

@medicamin are you also on Xorg?

**Comment by medicamin** [comment]
Yes I was on xorg because of some xdotool shortcuts. It seems it's the time to migrate to wayland...
Thank you for this point
