### ISSUE TITLE
Animations when first opening windows should be disabled.

### ISSUE THREAD

**Issue by freddyhayward** [rliang/gnome-shell-extension-window-animations#6]
### Expected behavior
When a window is opened, it should appear as is normal in vanilla shell.

### Actual behavior
Instead, windows appear to slide in from the top-left.

(Apologies for potato quality)
![a-o](https://user-images.githubusercontent.com/13117753/30061839-813d7f0e-9238-11e7-988a-d221c7b03a8c.gif)

**Comment by rliang** [comment]
Right. I'll see if there's a way to do this preferably without managing each window's state.
