### ISSUE TITLE
Half-tile animations don't work when pressing Meta+Left/Right for the first time.

### ISSUE THREAD

**Issue by freddyhayward** [rliang/gnome-shell-extension-window-animations#7]
### Expected behavior
Windows should animate when tiling after launching.

### Actual behavior
Tiling animations don't work after launching (maximising does work). Only subsequent animations work.
![output](https://user-images.githubusercontent.com/13117753/30108029-36b79d58-92f0-11e7-9cde-799b41ffcc5f.gif)

### Steps to reproduce the behavior
Open a window -> press meta+left/right

### GNOME version
3.24

**Comment by rliang** [comment]
Oh well, definitely a regression caused by fixing #6 .

Not sure how to solve both. Any help welcome.

**Comment by rliang** [comment]
Hi, please tell if the issue persists.

**Comment by freddyhayward** [comment]
Yes, both this and #6 seem to be fixed now.
