### ISSUE TITLE
gnome-terminal automatically moves on resize on wayland

### ISSUE THREAD

**Issue by freddyhayward** [rliang/gnome-shell-extension-window-animations#8]
### Expected behavior
After resizing, gnome-terminal should stay in place.

### Actual behavior
After resizing, gnome-terminal shifts upwards.
![gif-171007_142221](https://user-images.githubusercontent.com/13117753/31304427-366a9138-ab10-11e7-9d93-e0cae1cf5d63.gif)
I used a camera to avoid the hassle of screen recording on Wayland.

### Steps to reproduce the behavior
* Open a gnome session on wayland
* Open gnome-terminal
* Grab the top resize handle and drag up
* Release

### GNOME version
3.26 (Also happened on 3.24) with wayland

**Comment by rliang** [comment]
This happens because gnome-terminal doesn't allow itself to be resized in non-multiples of character width/height. Neither gnome-terminal nor mutter have any options to disable this.

So, I'm afraid this can't be fixed. But if you use another terminal emulator, this shouldn't happen.
